name: FoD results to GitHub

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Getting FoD results in SARIF format through Fortify Vulnerability Exporter
        uses: docker://fortifydocker/fortify-vulnerability-exporter:latest
        with:
          export_config: /config/FoDToGitHub.yml
          fod_baseUrl: ${{ secrets.FOD_AURL }}
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_userName: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RID }}
      - name: Uploading SARIF results into GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./gh-fortify-sast.sarif
